## Implementing Apriori Algorithm for Census Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
from apyori import apriori

In [2]:
census_data = pd.read_csv("D:\Data Science\Internship\Assignment\Problem\Problem1\census.csv", header = None)
num_records = len(census_data)
print(num_records)

30162

We can transform it into the right format i.e. a DF

In [3]:
records = []
for i in range(0, num_records):
    records.append([str(census_data.values[i,j]) for j in range(0, 12)])

In [4]:
records[0]

['age=Middle-aged',
 'sex=Male',
 'education=Bachelors',
 'native-country=United-States',
 'race=White',
 'marital-status=Never-married',
 'workclass=State-gov',
 'occupation=Adm-clerical',
 'hours-per-week=Full-time',
 'income=Small',
 'capital-gain=Low',
 'capital-loss=None']

In [5]:
association_rules = apriori(records, min_support = 0.3, min_confidence = 0.2, min_lift = 1, min_length = 2, max_length = 2)
association_results = list(association_rules)

In [6]:
print(len(association_results))

37

In [7]:
print(association_results[36])

RelationRecord(items=frozenset({'sex=Male', 'race=White'}), support=0.5980372654333267, ordered_statistics=[OrderedStatistic(items_base=frozenset({'race=White'}), items_add=frozenset({'sex=Male'}), confidence=0.6955616396097636, lift=1.0294175747747638), OrderedStatistic(items_base=frozenset({'sex=Male'}), items_add=frozenset({'race=White'}), confidence=0.8850834151128557, lift=1.029417574774764)])

In [8]:
results = []

for item in association_results[13:36]:
    pair = item[0]
    items = [x for x in pair]
    
    value0 = str(items[0])
    value1 = str(items[1])
    
    value2 = str(item[1]) #to convert into object
    
    value3 = str(item[2][0][2])
    value4 = str(item[2][0][3])
    
    rows = (value0, value1, value2, value3, value4)
    results.append(rows)
    
labels = ['Title 1', 'Title 2', 'Support', 'Confidence', 'Lift']

census = pd.DataFrame.from_records(results, columns = labels)

In [9]:
census

,Title 1,Title 2,Support,Confidence,Lift
0,age=Middle-aged,hours-per-week=Full-time,0.31005901465420066,0.5935893367185021,1.0112879334672087
1,age=Middle-aged,sex=Male,0.3638684437371527,0.6966042526182165,1.0309606215638196
2,age=Middle-aged,workclass=Private,0.3887673231218089,0.7442716597905427,1.007301525738237
3,education=HS-grad,capital-gain=None,0.30498640673695376,0.33300752968433245,1.0207492998311825
4,hours-per-week=Full-time,capital-gain=None,0.5445925336516146,0.5946278598320301,1.0130572474160469
5,income=Small,capital-gain=None,0.7198130097473643,0.7859470026064292,1.0464259509408986
6,marital-status=Never-married,capital-gain=None,0.30833499104833895,0.3366637706342311,1.0440522979508202
7,capital-gain=None,sex=Female,0.3057158013394337,0.33380393860411234,1.0292572476157469
8,workclass=Private,capital-gain=None,0.6824149592202109,0.745112945264987,1.0084401263161866
9,education=HS-grad,capital-loss=None,0.3136396790663749,0.3292152427353402,1.0091250153844848
10,hours-per-week=Full-time,capital-loss=None,0.5626284729129368,0.5905689925178355,1.0061422250521326
11,income=Small,capital-loss=None,0.7282010476758836,0.7643640160083522,1.0176899201396628
12,marital-status=Never-married,capital-loss=None,0.31300974736423315,0.3285540281886202,1.01890259081073
13,capital-loss=None,sex=Female,0.31314236456468403,0.3286932312510875,1.013498797893611
14,workclass=Private,capital-loss=None,0.7070486042039652,0.742161127544806,1.0044451193128618
15,native-country=United-States,education=HS-grad,0.305317949738081,0.9358739837398374,1.0263173028490755
16,income=Small,hours-per-week=Full-time,0.46900072939460247,0.7990284681427926,1.0638428823220143
17,hours-per-week=Full-time,workclass=Private,0.44715204562031696,0.7618052417532761,1.0310315759563096
18,income=Small,marital-status=Never-married,0.3068762018433791,0.4085812660015891,1.2670808292350328
19,income=Small,workclass=Private,0.5772163649625356,0.7685177010682439,1.0401162568258266
20,race=White,marital-status=Married-civ-spouse,0.4196008222266428,0.8998222538215428,1.046559935979847
21,sex=Male,marital-status=Married-civ-spouse,0.4172468669186393,0.8947742623533593,1.3242483464721306
22,native-country=United-States,race=White,0.8029308401299649,0.8805264688772542,1.024117508744678

<b>Sorting dataframe by Confidence

In [10]:
census.sort_values('Confidence', ascending = False, inplace = True)

In [11]:
census[['Lift', 'Confidence', 'Support']] = census[['Lift', 'Confidence', 'Support']].astype(float)

In [12]:
census

,Title 1,Title 2,Support,Confidence,Lift
15,native-country=United-States,education=HS-grad,0.305318,0.935874,1.026317
20,race=White,marital-status=Married-civ-spouse,0.419601,0.899822,1.046560
21,sex=Male,marital-status=Married-civ-spouse,0.417247,0.894774,1.324248
22,native-country=United-States,race=White,0.802931,0.880526,1.024118
16,income=Small,hours-per-week=Full-time,0.469001,0.799028,1.063843
5,income=Small,capital-gain=None,0.719813,0.785947,1.046426
19,income=Small,workclass=Private,0.577216,0.768518,1.040116
11,income=Small,capital-loss=None,0.728201,0.764364,1.017690
17,hours-per-week=Full-time,workclass=Private,0.447152,0.761805,1.031032
8,workclass=Private,capital-gain=None,0.682415,0.745113,1.008440
2,age=Middle-aged,workclass=Private,0.388767,0.744272,1.007302
14,workclass=Private,capital-loss=None,0.707049,0.742161,1.004445
1,age=Middle-aged,sex=Male,0.363868,0.696604,1.030961
4,hours-per-week=Full-time,capital-gain=None,0.544593,0.594628,1.013057
0,age=Middle-aged,hours-per-week=Full-time,0.310059,0.593589,1.011288
10,hours-per-week=Full-time,capital-loss=None,0.562628,0.590569,1.006142
18,income=Small,marital-status=Never-married,0.306876,0.408581,1.267081
6,marital-status=Never-married,capital-gain=None,0.308335,0.336664,1.044052
7,capital-gain=None,sex=Female,0.305716,0.333804,1.029257
3,education=HS-grad,capital-gain=None,0.304986,0.333008,1.020749
9,education=HS-grad,capital-loss=None,0.313640,0.329215,1.009125
13,capital-loss=None,sex=Female,0.313142,0.328693,1.013499
12,marital-status=Never-married,capital-loss=None,0.313010,0.328554,1.018903

In [13]:
census.dtypes

Title 1        object
Title 2        object
Support       float64
Confidence    float64
Lift          float64
dtype: object

<b>Resetting index

In [14]:
census.reset_index(drop = True, inplace = True)
census

,Title 1,Title 2,Support,Confidence,Lift
0,native-country=United-States,education=HS-grad,0.305318,0.935874,1.026317
1,race=White,marital-status=Married-civ-spouse,0.419601,0.899822,1.046560
2,sex=Male,marital-status=Married-civ-spouse,0.417247,0.894774,1.324248
3,native-country=United-States,race=White,0.802931,0.880526,1.024118
4,income=Small,hours-per-week=Full-time,0.469001,0.799028,1.063843
5,income=Small,capital-gain=None,0.719813,0.785947,1.046426
6,income=Small,workclass=Private,0.577216,0.768518,1.040116
7,income=Small,capital-loss=None,0.728201,0.764364,1.017690
8,hours-per-week=Full-time,workclass=Private,0.447152,0.761805,1.031032
9,workclass=Private,capital-gain=None,0.682415,0.745113,1.008440
10,age=Middle-aged,workclass=Private,0.388767,0.744272,1.007302
11,workclass=Private,capital-loss=None,0.707049,0.742161,1.004445
12,age=Middle-aged,sex=Male,0.363868,0.696604,1.030961
13,hours-per-week=Full-time,capital-gain=None,0.544593,0.594628,1.013057
14,age=Middle-aged,hours-per-week=Full-time,0.310059,0.593589,1.011288
15,hours-per-week=Full-time,capital-loss=None,0.562628,0.590569,1.006142
16,income=Small,marital-status=Never-married,0.306876,0.408581,1.267081
17,marital-status=Never-married,capital-gain=None,0.308335,0.336664,1.044052
18,capital-gain=None,sex=Female,0.305716,0.333804,1.029257
19,education=HS-grad,capital-gain=None,0.304986,0.333008,1.020749
20,education=HS-grad,capital-loss=None,0.313640,0.329215,1.009125
21,capital-loss=None,sex=Female,0.313142,0.328693,1.013499
22,marital-status=Never-married,capital-loss=None,0.313010,0.328554,1.018903

In [37]:
def arrangingRules(rules):
    for i in rules.index:
        val = rules.loc[i,'Confidence']
        if val >= 0.70:
            print(val)

In [38]:
arrangingRules(census)

0.9358739837398374
0.8998222538215428
0.8947742623533593
0.8805264688772542
0.7990284681427926
0.7859470026064292
0.7685177010682439
0.7643640160083522
0.7618052417532761
0.745112945264987
0.7442716597905427
0.742161127544806